# Generated by Django 3.1.6 on 2021-03-12 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210223_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=10, null=True)),
                ('price', models.CharField(max_length=5, null=True)),
                ('payment_status', models.CharField(max_length=2, null=True)),
                ('transection', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.users')),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
    ]
